name: criterion-scraper
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - dotenv
  - mtl
  - postgresql-simple
  - raw-strings-qq
  - resource-pool
  - scalpel
  - servant
  - servant-server
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - warp

default-extensions:
  - BlockArguments
  - DataKinds
  - FlexibleContexts
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src

executables:
  criterion-scraper:
    dependencies: criterion-scraper
    ghc-options: -threaded -O "-with-rtsopts=-N"
    source-dirs: "./app"
    main: Main.hs

tests:
  criterion-scraper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - criterion-scraper
