name: criterion-scraper
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - dotenv
  - lens
  - mtl
  - postgresql-simple
  - raw-strings-qq
  - scalpel
  - sqlite-simple # TODO: Delete
  - text

default-extensions:
  - BlockArguments
  - FlexibleContexts
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings

library:
  source-dirs: src

tests:
  criterion-scraper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - criterion-scraper
